language: python

python:
  - 2.6
  - 2.7
  - pypy
  - 3.2
  - 3.3
  - 3.4
  - nightly
  - pypy3

addons:
  firefox: "31.0"
  apt:
    packages:
      - xvfb

install: 
  - python setup.py develop
  - python setup.py install

script:
  - which Xvfb
  - which firefox
  - nosetests
