#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# firefox-connector - Firefox tests
#


from funicular.browsers.firefox.connector import FirefoxConnector
import argparse
import logging

# Configuration des paramètres
parser = argparse.ArgumentParser()
parser.add_argument("-d", "--debug", help="debug mode", action="store_true")
parser.add_argument("-u", "--load", help="url to load", default="http://www.google.fr")
parser.add_argument("-p", "--png", help="png to save", default="out.png")
parser.add_argument("-t", "--timeout", help="timeout in seconds", default=5)

# Récupération des paramètres
args = parser.parse_args()

# Initialisation du logger
if args.debug:
    logging.basicConfig(level=logging.DEBUG)
else:
    logging.basicConfig(level=logging.WARNING)
logger = logging.getLogger(__name__)

connector = FirefoxConnector(timeout=10, logger=logger)
connector.connect()
connector.execute('%s.look();' % (connector._instance_name,))
connector = None
